steps:
  - name: node:10.15.1
    entrypoint: yarn
    args: ["add", "firebase-tools"]
  - name: "node:10.15.1"
    entrypoint: "./node_modules/.bin/firebase"
    args: ["deploy", "--project", ${{ secrets.PROJECT_ID }}, "--token", ${{ secrets.FIREBASE_TOKEN }}]